#!/bin/bash

# Check for ssh host keys, regenerate them if needed
if [ ! -f /etc/ssh/ssh_host_ed25519_key ] || \
   [ ! -f /etc/ssh/ssh_host_ecdsa_key ] || \
   [ ! -f /etc/ssh/ssh_host_rsa_key ]; then
    echo "Regenerating sshd host keys..." >&2

    if [ -c /dev/hwrng ]; then
        dd if=/dev/hwrng of=/dev/urandom count=1 bs=4096 status=none
    fi
    rm -f /etc/ssh/ssh_host_*_key*
    ssh-keygen -A > /dev/null

    systemctl disable regenerate_ssh_host_keys.service
fi
