#!/bin/sh

if [ $(id -u) -ne 0 ] ; then
  echo "Please run as root" >&2
  exit 1
fi

if grep " / " /proc/mounts |grep -q ' rw'; then
  mount -o remount,ro /
fi

if grep /boot /proc/mounts |grep -q ' rw'; then
  mount -o remount,ro /boot
fi
