#!/bin/sh

if [ $(id -u) -ne 0 ] ; then
  echo "Please run as root" >&2
  exit 1
fi

if grep " / " /proc/mounts | grep -q ' ro'; then
  mount -o remount,rw /
fi

if grep /boot /proc/mounts | grep -q ' ro'; then
  mount -o remount,rw /boot
fi
